version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blogAppUser -d blogAppDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: url/repo_name:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://database_user:database_password@postgres:5432/database_name
      NODE_ENV: production
      OPENROUTER: yourkeyhere
      GEMINI_API_KEY: yourkeyhere
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: url/repo_name:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://backend:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
